"use strict";
import { BaseContract, Contract, ContractFactory } from "@exchain-ethersproject/contracts";
import { BigNumber, FixedNumber } from "@exchain-ethersproject/bignumber";
import { Signer, VoidSigner } from "@exchain-ethersproject/abstract-signer";
import { Wallet } from "@exchain-ethersproject/wallet";
import * as constants from "@exchain-ethersproject/constants";
import * as providers from "@exchain-ethersproject/providers";
import { getDefaultProvider } from "@exchain-ethersproject/providers";
import { Wordlist, wordlists } from "@exchain-ethersproject/wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "@exchain-ethersproject/logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=ethers.js.map